### ISSUE TITLE
US#2TK#8 Generar funcion para la categoria Terremoto generando tabla y csv

### ISSUE THREAD

**Issue by Gona79** [ispc-programador2022/UYVV4#11]
**US#2TK#8** 

Crear una funcion Terremoto.py que: 

- [ ] Genere tabla con web scraping de pagina https://ourworldindata.org/natural-disasters#data-quality
- [ ] Genere un  CSV a partir de esta tabla

**Comment by marianovila** [comment]
Se sube al repositorio archivo py más csv exportado.

**Comment by marianovila** [comment]
Buenas! se resube el archivo con nombre cambiado, más el csv y el readme actualizado. Saludos!
