### ISSUE TITLE
US#2TK#12 Generar funcion para la categoria Aludes generando tabla y csv

### ISSUE THREAD

**Issue by Gona79** [ispc-programador2022/UYVV4#15]
**US#2TK#12** 

Crear una funcion Aludes.py que: 

- [ ] Genere tabla con web scraping de pagina https://ourworldindata.org/natural-disasters#data-quality
- [ ] Genere un  CSV a partir de esta tabla

**Comment by marianovila** [comment]
Se sube al repositorio archivo py más csv exportado.
