### ISSUE TITLE
US#2TK#13 Generar funcion para la categoria Incendios Forestales generando tabla y csv

### ISSUE THREAD

**Issue by Gona79** [ispc-programador2022/UYVV4#16]
**US#2TK#13** 

Crear una funcion IncendiosForestales.py que: 

- [x] Genere tabla con web scraping de pagina https://ourworldindata.org/natural-disasters#data-quality
- [x] Genere un  CSV a partir de esta tabla

**Comment by Mar-Urzag** [comment]
Listas las tareas.

**Comment by Gona79** [comment]
Gise cargaste las dos soluciones en tormentas, asi que no se realiza el pull request de incendios. 

![image](https://user-images.githubusercontent.com/84986194/202263080-a7fbefb1-4642-4fbb-8b7f-29f4c9b9d809.png)
