### ISSUE TITLE
US#1TK#3 Crear Kanban en Trello

### ISSUE THREAD

**Issue by Gona79** [ispc-programador2022/UYVV4#4]
Crear un Kanban en trello, los reauisitos son: 

- [x] Debe contener el proyecto solicitado
- [x] Debe integrar al TEAM
- [x] Se debe mostrar el product backlon
- [x] Debe integrar la participacion del tutor "ispc.programador2022@gmail.com"

**Comment by marianovila** [comment]
Buenas, ya están los integrantes y el correo institucional invitado al tablero de Trello

**Comment by marianovila** [comment]
Tarea finalizada, se cierra
