### ISSUE TITLE
US#1TK#5 Definir la pagina web del scrapping de datos

### ISSUE THREAD

**Issue by Gona79** [ispc-programador2022/UYVV4#6]
**Definir las paginas para el scrapping en paginas sobre desastres naturales**

- [x] buscar paginas en español
- [x] bucar paginas en ingles

**Comment by clau-yon** [comment]
- https://www.desinventar.net/DesInventar/
- https://ourworldindata.org/natural-disasters#data-quality
- https://www.emdat.be/
